[env:m5stack-papercolor]
platform = espressif32 @ 6.12.0
board = esp32s3box
framework = arduino
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
build_flags =
  -DESP32S3
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
lib_deps =
  m5stack/M5Unified @ 0.2.19
  m5stack/M5GFX @ 0.2.26
  bblanchon/ArduinoJson @ ^7.4.2
  tzapu/WiFiManager @ ^2.0.17
